const filterDescriptions = [
    { url: "abarth", description: "Abarth" },
    { url: "acura", description: "Acura" },
    { url: "aiways", description: "Aiways" },
    { url: "aixam", description: "Aixam" },
    { url: "alfa-romeo", description: "Alfa Romeo" },
    { url: "alpina", description: "Alpina" },
    { url: "alpine", description: "Alpine" },
    { url: "arcfox", description: "Arcfox" },
    { url: "asia", description: "Asia" },
    { url: "aston-martin", description: "Aston Martin" },
    { url: "audi", description: "Audi" },
    { url: "austin", description: "Austin" },
    { url: "autobianchi", description: "Autobianchi" },
    { url: "avatr", description: "Avatr" },
    { url: "baic", description: "BAIC" },
    { url: "bentley", description: "Bentley" },
    { url: "bmw", description: "BMW" },
    { url: "brilliance", description: "Brilliance" },
    { url: "bugatti", description: "Bugatti" },
    { url: "buick", description: "Buick" },
    { url: "byd", description: "BYD" },
    { url: "cadillac", description: "Cadillac" },
    { url: "casalini", description: "Casalini" },
    { url: "caterham", description: "Caterham" },
    { url: "cenntro", description: "Cenntro" },
    { url: "changan", description: "Changan" },
    { url: "chatenet", description: "Chatenet" },
    { url: "chevrolet", description: "Chevrolet" },
    { url: "chrysler", description: "Chrysler" },
    { url: "citroen", description: "Citroën" },
    { url: "cupra", description: "Cupra" },
    { url: "dacia", description: "Dacia" },
    { url: "daewoo", description: "Daewoo" },
    { url: "daihatsu", description: "Daihatsu" },
    { url: "delorean", description: "DeLorean" },
    { url: "dfm", description: "DFM" },
    { url: "dfsk", description: "DFSK" },
    { url: "dkw", description: "DKW" },
    { url: "dodge", description: "Dodge" },
    { url: "doosan", description: "Doosan" },
    { url: "dr-motor", description: "DR Motor" },
    { url: "ds-automobiles", description: "DS Automobiles" },
    { url: "e-go", description: "e.GO" },
    { url: "elaris", description: "Elaris" },
    { url: "faw", description: "FAW" },
    { url: "fendt", description: "Fendt" },
    { url: "ferrari", description: "Ferrari" },
    { url: "fiat", description: "Fiat" },
    { url: "fisker", description: "Fisker" },
    { url: "ford", description: "Ford" },
    { url: "forthing", description: "Forthing" },
    { url: "gaz", description: "GAZ" },
    { url: "geely", description: "Geely" },
    { url: "genesis", description: "Genesis" },
    { url: "gmc", description: "GMC" },
    { url: "gwm", description: "GWM" },
    { url: "hiphi", description: "HiPhi" },
    { url: "honda", description: "Honda" },
    { url: "hongqi", description: "Hongqi" },
    { url: "hummer", description: "Hummer" },
    { url: "hyundai", description: "Hyundai" },
    { url: "iamelectric", description: "I Am Electric" },
    { url: "ineos", description: "Ineos" },
    { url: "infiniti", description: "Infiniti" },
    { url: "isuzu", description: "Isuzu" },
    { url: "iveco", description: "Iveco" },
    { url: "jac", description: "JAC" },
    { url: "jaecoo", description: "Jaecoo" },
    { url: "jaguar", description: "Jaguar" },
    { url: "jeep", description: "Jeep" },
    { url: "jetour", description: "Jetour" },
    { url: "jinpeng", description: "Jinpeng" },
    { url: "kia", description: "Kia" },
    { url: "ktm", description: "KTM" },
    { url: "lada", description: "Lada" },
    { url: "lamborghini", description: "Lamborghini" },
    { url: "lancia", description: "Lancia" },
    { url: "land-rover", description: "Land Rover" },
    { url: "leapmotor", description: "Leapmotor" },
    { url: "levc", description: "LEVC" },
    { url: "lexus", description: "Lexus" },
    { url: "ligier", description: "Ligier" },
    { url: "lincoln", description: "Lincoln" },
    { url: "lixiang", description: "LiXiang" },
    { url: "lotus", description: "Lotus" },
    { url: "lti", description: "LTI" },
    { url: "lucid", description: "Lucid" },
    { url: "lynk-and-co", description: "Lynk & Co" }
];
